### ISSUE TITLE
Create an App Icon

### ISSUE THREAD

**Issue by schmelto** [schmelto/NewsApp#28]
May you want to create an app icon for the NewsApp.

**Comment by adityaraute** [comment]
What kind of a design are you looking out for?

**Comment by schmelto** [comment]
> What kind of a design are you looking out for?

@adityaraute i thought like something in flat or material design but you are free to make something you want :)

**Comment by schmelto** [comment]
![image](https://user-images.githubusercontent.com/30869493/108114834-952d1900-7099-11eb-89d7-08f2e3ddd448.png)

**Comment by adityaraute** [comment]
Sorry I never got to it. This looks cool.
